### ISSUE TITLE
Feature: Heart beat and uptime/health check

### ISSUE THREAD

**Issue by Vadorequest** [Financial-Times/serverless-plugin-healthcheck#1]
This plugin solves the heart beat issue by sending scheduled requests to avoid the lambda to go to sleep and keep it warm. It's very nice and I intend to use it.

But I also think it could solve the "uptime check". I discovered Uptime Check in Google Cloud Platform, and it's translated as Health Check in AWS:

- https://cloud.google.com/monitoring/uptime-checks/

Since this plugin already does what you call a "health check" (but isn't really a health check, not the same health check as AWS), it makes sense to include some kind of feedback alert when things go down, wouldn't it ?

Something like this (specs to be defined):

```yml
functions:
  hello:
    events
      - http:
          path: /schema/{TypeID}/{ItemID}
          method: get
          private: false
          healthcheck:
            params: {"subjectType": "system", "subjectID": "dewey"}
            alert: 
              email: admin@mydomain.com
```

The idea is just to react when something is wrong, by sending alerts somehow.

I don't know if this can already be done with this plugin. I don't know if it's something you want to do. But if it is already possible then it would be nice to add examples for email, sms and slack alerts.
